src/main/java/de/wernertoex/supporttx/controller/EmailController.java
package de.wernertoex.supporttx.controller;

import java.io.Serializable;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import de.wernertoex.supporttx.util.MailerBean;

@Named
@RequestScoped
public class EmailController implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -2220497968519386863L;

	@Inject
	private MailerBean mailer;
	
	private String mailBody;
	private String mailSubject;
	private String toMailAdress;
	
	
	
	public String getMailBody() {
		return mailBody;
	}
	public void setMailBody(String mailBody) {
		this.mailBody = mailBody;
	}
	public String getMailSubject() {
		return mailSubject;
	}
	public void setMailSubject(String mailSubject) {
		this.mailSubject = mailSubject;
	}
	public String getToMailAdress() {
		return toMailAdress;
	}
	public void setToMailAdress(String toMailAdress) {
		this.toMailAdress = toMailAdress;
	}
	
	public String sendMail(){
		mailer.setMailBody(mailBody);
		mailer.setMailSubject(mailSubject);
		mailer.setToAdress(toMailAdress);
		mailer.sendMail();
		return "";
	}
	
	
	
}

src/main/java/de/wernertoex/supporttx/controller/KundeController.java
package de.wernertoex.supporttx.controller;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Logger;

import javax.enterprise.context.SessionScoped;
import javax.enterprise.event.Event;
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.commons.lang.StringUtils;

import de.wernertoex.supporttx.data.Kunde;
import de.wernertoex.supporttx.data.Mitarbeiter;
import de.wernertoex.supporttx.repositories.KundeRepository;
import de.wernertoex.supporttx.repositories.MitarbeiterRepository;
import de.wernertoex.supporttx.util.MailerBean;
import de.wernertoex.supporttx.util.Events.Added;
import de.wernertoex.supporttx.util.Events.Deleted;
import de.wernertoex.supporttx.util.Events.Updated;
import de.wernertoex.supporttx.util.LoggerQual.FachLog;

@SessionScoped
@Named
public class KundeController implements Serializable {

	private static final long serialVersionUID = -4209172851479439592L;

	@Inject
	@Added
	private Event<Kunde> kundeAddEvent;

	@Inject
	@Updated
	private Event<Kunde> kundeUpdateEvent;

	@Inject
	@Deleted
	private Event<Mitarbeiter> mitarbeiterDeleteEvent;
	
	@Inject
	private KundeRepository kundeRepository;

	@Inject
	private MitarbeiterRepository mitarbeiterRepository;

	@Inject
	private KundeUebersichtController kundeUebersichtController;

	@Inject
	private MitarbeiterController mitarbeiterController;

	@Inject
	private EmailController emailController;
	
	@Inject
	@FachLog
	private Logger logger;

	private Kunde kunde;
	private ControllerModes mode;
	private List<Mitarbeiter> mitarbeiters;

	private ControllerModes getMode() {
		return mode;
	}

	void loadMitarbeiter() {
		mitarbeiters = mitarbeiterRepository.findByKunde(kunde);
	}

	public void setKundeToEdit(ControllerModes mode) {
		setKundeToEdit(mode, new Kunde());
	}

	public void setKundeToEdit(ControllerModes mode, Kunde kunde) {
		this.kunde = kunde;
		this.mode = mode;
		loadMitarbeiter();
	}

	public String doSave() {
		if (getMode() == ControllerModes.ADD) {
			kundeRepository.persist(kunde);
			kundeAddEvent.fire(kunde);
		}
		if (getMode() == ControllerModes.EDIT) {
			kunde = kundeRepository.saveEntity(kunde);
			kundeUpdateEvent.fire(kunde);
		}
		kundeUebersichtController.init();
		return Pages.KUNDE_UEBERSICHT;
	}

	public String doCancel() {
		return Pages.KUNDE_UEBERSICHT;
	}

	public String getTitle() {
		return getMode() == ControllerModes.EDIT ? "Kunde editieren"
				: "Neuen Kunden anlegen";
	}

	public Kunde getKunde() {
		return kunde;
	}

	public void setKunde(Kunde kunde) {
		this.kunde = kunde;
	}

	public String doAddMitarbeiter() {
		System.out.println("Add Aktion");
		mitarbeiterController.setMitarbeiterToEdit(ControllerModes.ADD, kunde);
		return Pages.MITARBEITER_EDIT;
	}

	public String doEditMitarbeiter(Mitarbeiter mitarbeiter) {
		mitarbeiterController.setMitarbeiterToEdit(ControllerModes.EDIT,
				mitarbeiter);
		return Pages.MITARBEITER_EDIT;
	}

	public void doDeleteMitarbeiter(Mitarbeiter mitarbeiter) {
		mitarbeiterRepository.delete(mitarbeiter);
		mitarbeiterDeleteEvent.fire(mitarbeiter);
		
	}

	public List<Mitarbeiter> getMitarbeiters() {
		return mitarbeiters;
	}

	public void setMitarbeiters(List<Mitarbeiter> mitarbeiters) {
		this.mitarbeiters = mitarbeiters;
	}

	public void onMitarbeiterAdded(@Observes @Added Mitarbeiter mitarbeiter) {
		logger.info("Mitarbeiter hinzugefügt");
		mitarbeiters.add(mitarbeiter);
	}

	public void onMitarbeiterDeleted(@Observes @Deleted Mitarbeiter mitarbeiter) {
		mitarbeiters.remove(mitarbeiter);
	}

	public void onMitarbeiterUpdated(@Observes @Updated Mitarbeiter mitarbeiter) {
		logger.info("Mitarbeiter aktualisiert");
		mitarbeiters.remove(mitarbeiter);
		mitarbeiters.add(mitarbeiter);
	}

	public boolean isEditable(){
		return this.mode == ControllerModes.ADD || this.mode == ControllerModes.EDIT;
	}
	
	public String doMitarbeiterMail(Mitarbeiter mitarbeiter){
		if (!StringUtils.isBlank(mitarbeiter.getEmail())){
			emailController.setToMailAdress(mitarbeiter.getEmail());
			return Pages.EMAIL;
		}
		return "";
	}
	
}

src/main/java/de/wernertoex/supporttx/controller/KundeUebersichtController.java
package de.wernertoex.supporttx.controller;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.enterprise.event.Event;
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import javax.inject.Named;

import de.wernertoex.supporttx.application.MyApplication;
import de.wernertoex.supporttx.data.Kunde;
import de.wernertoex.supporttx.repositories.KundeRepository;
import de.wernertoex.supporttx.util.Events.Added;
import de.wernertoex.supporttx.util.Events.Deleted;
import de.wernertoex.supporttx.util.Events.Updated;
import de.wernertoex.supporttx.util.LoggerQual.FachLog;

@Named
@SessionScoped
public class KundeUebersichtController implements Serializable {

	private static final long serialVersionUID = -5872397484519155109L;

	private List<Kunde> kunden;
	private List<Kunde> filteredKunden;
	
	private Kunde selectedKunde;
	
	@Inject @FachLog
	Logger logger;
	
	@Inject
	@Deleted
	private Event<Kunde> kundeDeleteEvent;

	@Inject
	private MyApplication myApplication;

	@Inject
	private KundeRepository kundenRepository;

	@Inject
	private KundeController kundeController;
	
	public List<Kunde> getKunden() {		
		return kunden;
	}

	@PostConstruct
	void init(){
		myApplication.init(); 
		kunden= kundenRepository.findAll();			
	}

	public String doAddKunde(){
		System.out.println("Add Aktion");
		kundeController.setKundeToEdit(ControllerModes.ADD);
		return Pages.KUNDE_EDIT;
	}
	
	public String doEditKunde(Kunde kunde){
		kundeController.setKundeToEdit(ControllerModes.EDIT, kunde);
		return Pages.KUNDE_EDIT;
	}
	
	public String doShowKunde(Kunde kunde){
		logger.info("doShowKunde");
		kundeController.setKundeToEdit(ControllerModes.SHOW, kunde);
		return Pages.KUNDE_EDIT;
	}
	
	public void doDeleteKunde(Kunde kunde){
		kundenRepository.delete(kunde);
		kundeDeleteEvent.fire(kunde);
	}
	
	public Kunde getSelectedKunde() {
		return selectedKunde;
	}

	public void setSelectedKunde(Kunde selectedKunde) {
		this.selectedKunde = selectedKunde;
	}

	public List<Kunde> getFilteredKunden() {
		return filteredKunden;
	}

	public void setFilteredKunden(List<Kunde> filteredKunden) {
		this.filteredKunden = filteredKunden;
	}
	
	public void onKundeAddEvent(@Observes @Added Kunde kunde){
		this.kunden.add(kunde);
		logger.info("Kunde hinzugefügt");
	}
	
	public void onKundeUpdateEvent(@Observes @Updated Kunde kunde){
		int index = kunden.indexOf(kunde);
		if (index >=0)
		this.kunden.set(index,kunde);
	}
	
	public void onKundeDeleteEvent(@Observes @Deleted Kunde kunde){
		kunden.remove(kunde);
	}
	
}

src/main/java/de/wernertoex/supporttx/controller/MitarbeiterController.java
package de.wernertoex.supporttx.controller;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.enterprise.event.Event;
import javax.inject.Inject;
import javax.inject.Named;

import de.wernertoex.supporttx.data.Kunde;
import de.wernertoex.supporttx.data.Mitarbeiter;
import de.wernertoex.supporttx.repositories.MitarbeiterRepository;
import de.wernertoex.supporttx.util.Events.Added;
import de.wernertoex.supporttx.util.Events.Updated;

@SessionScoped
@Named
public class MitarbeiterController implements Serializable {

	private static final long serialVersionUID = -4209172851479439592L;

	@Inject
	@Added
	private Event<Mitarbeiter> mitarbeiterAddEventSrc;

	@Inject
	@Updated
	private Event<Mitarbeiter> mitarbeiterUpdateEventSrc;

	@Inject
	private MitarbeiterRepository repository;

	private Mitarbeiter mitarbeiter;
	private ControllerModes mode;

	private ControllerModes getMode() {
		return mode;
	}

	public void setMitarbeiterToEdit(ControllerModes mode, Kunde kunde) {
		Mitarbeiter newMitarbeiter = new Mitarbeiter();
		newMitarbeiter.setKunde(kunde);
		setMitarbeiterToEdit(mode, newMitarbeiter);
	}

	public void setMitarbeiterToEdit(ControllerModes mode,
			Mitarbeiter mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
		this.mode = mode;
	}

	public String doSave() {
		if (getMode() == ControllerModes.ADD) {
			repository.persist(mitarbeiter);
			mitarbeiterAddEventSrc.fire(mitarbeiter); 
		}
		if (getMode() == ControllerModes.EDIT) {
			mitarbeiter = repository.saveEntity(mitarbeiter);
			mitarbeiterUpdateEventSrc.fire(mitarbeiter);
		}
		return Pages.KUNDE_EDIT;
	}

	public String doCancel() {
		return Pages.KUNDE_EDIT;
	}

	public String getTitle() {
		return getMode() == ControllerModes.EDIT ? "Kunde editieren"
				: "Neuen Kunden anlegen";
	}

	public Mitarbeiter getMitarbeiter() {
		return mitarbeiter;
	}

	public void setMitarbeiter(Mitarbeiter mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
	}

}

src/main/java/de/wernertoex/supporttx/util/MailerBean.java
package de.wernertoex.supporttx.util;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;

import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.HtmlEmail;

import de.wernertoex.supporttx.util.LoggerQual.TecLog;

@SessionScoped
public class MailerBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2723681094867331593L;

	@Inject
	@TecLog
	Logger logger;

	private HtmlEmail email = new HtmlEmail();

	private String toAdress;
	private String fromAdress;
	private String mailSubject;
	private String mailBody;
	private String smtpServer;
	private String smtpHost;
	private String smtpPwd;

	public String getToAdress() {
		return toAdress;
	}

	public void setToAdress(String toAdress) {
		this.toAdress = toAdress;
	}

	public String getFromAdress() {
		return fromAdress;
	}

	public void setFromAdress(String fromAdress) {
		this.fromAdress = fromAdress;
	}

	public String getMailBody() {
		return mailBody;
	}

	public void setMailBody(String mailBody) {
		this.mailBody = mailBody;
	}

	public String getMailSubject() {
		return mailSubject;
	}

	public void setMailSubject(String mailSubject) {
		this.mailSubject = mailSubject;
	}

	public void sendMail() {
		// Create the email message
		try {
			email.setHostName("smtp.1und1.de");
			email.addTo(toAdress);
			email.setFrom("webmaster@ksl-kommunal.de", "Me");
			email.setAuthentication("webmaster@ksl-kommunal.de", "*maLi81#wjT75/");
			email.setSSL(true);
			email.setSmtpPort(587);
			email.setSubject(mailSubject);

			// set the html message
			email.setHtmlMsg(mailBody);

			// set the alternative message
			email.setTextMsg("Your email client does not support HTML messages");

			// send the email
			email.send();
		} catch (EmailException ee) {
			logger.severe("Mail fehlgeschlagen: " + ee.toString());
		}
	}

}

src/main/webapp/EMail.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


<ui:composition template="WEB-INF/templates/template.xhtml">
	<ui:define name="content">

		<h:head>
			<title>E-Mail senden - supportTX</title>
		</h:head>
		<h:form>
			<p:commandButton value="Senden" icon="ui-icon-mail-closed"
				action="#{emailController.sendMail()}" ajax="false" />
			<p:commandButton value="Abbrechen" icon="ui-icon-close"
				action="#{mitarbeiterController.doCancel()}" ajax="false" />
			<hr />
			<h3 style="padding-left: 20">E-Mail senden</h3>
			<p:panelGrid columns="2">
				<p:outputLabel id="lblempfaenger">Empfänger:</p:outputLabel>
				<p:inputText value="#{emailController.toMailAdress}"
					label="lblempfaenger" size="40" placeholder="Empfänger" />
				<p:outputLabel id="lblSubject">Betreff:</p:outputLabel>
				<p:inputText value="#{emailController.mailSubject}"
					label="lblSubject" placeholder="Betreff" size="200" />
			</p:panelGrid>
			<p:editor value="#{emailController.mailBody}"></p:editor>


		</h:form>


	</ui:define>
</ui:composition>
</html>

src/main/webapp/KundeEdit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


<ui:composition template="WEB-INF/templates/template.xhtml">

	<ui:define name="content">

		<h:form>
			<p:commandButton value="Speichern" icon="ui-icon-disk"
				action="#{kundeController.doSave()}" ajax="false"
				rendered="#{kundeController.editable}" />
			<p:commandButton value="Abbrechen" icon="ui-icon-close"
				action="#{kundeController.doCancel()}" ajax="false" />
			<p:commandButton value="Neuer Mitarbeiter" icon="ui-icon-plus"
				action="#{kundeController.doAddMitarbeiter()}" ajax="false"
				rendered="#{kundeController.editable}" />
			<hr />
			<h3 style="padding-left: 20">Kunde bearbeiten</h3>
			<p:panelGrid columns="2" style="padding-top:20">
				<p:outputLabel id="lblKunde">Kunde:</p:outputLabel>
				<p:inputText value="#{kundeController.kunde.kdName}"
					label="lblKunde" size="40" placeholder="Kunde" />
				<p:outputLabel id="lblStrasse">Straße:</p:outputLabel>
				<p:inputText value="#{kundeController.kunde.anschrift}"
					label="lblStrasse" placeholder="Straße" size="40" />
				<p:outputLabel id="lblPLZ">PLZ:</p:outputLabel>
				<p:inputText value="#{kundeController.kunde.plz}" label="lblPLZ"
					placeholder="PLZ" size="20" />

				<p:outputLabel id="lblOrt">Ort:</p:outputLabel>
				<p:inputText value="#{kundeController.kunde.ort}" label="lblOrt"
					placeholder="Ort" size="40" />
				<p:outputLabel id="lblTelefon">Telefon:</p:outputLabel>
				<p:inputText value="#{kundeController.kunde.telefon}"
					label="lblTelefon" placeholder="Telefon" size="40" />
				<p:outputLabel id="lblTelefax">Telefax:</p:outputLabel>
				<p:inputText value="#{kundeController.kunde.telefax}"
					label="lblTelefax" placeholder="Telefax" size="40" />
				<p:outputLabel id="lblemail">E-Mail:</p:outputLabel>
				<p:inputText value="#{kundeController.kunde.email}" label="lblemail"
					placeholder="E-Mail" size="40" />
			</p:panelGrid>
		</h:form>
		<hr />
		<h:form rendered="#{kundeController.kunde.id>0}">

			<p:dataTable var="mitarbeiter"
				value="#{kundeController.mitarbeiters}" paginator="false" rows="5">
				<f:facet name="header">
               Mitarbeiter
        </f:facet>
				<p:column style="width:15">
					<p:commandButton icon="ui-icon-trash" onclick="confirmation.show()"
						actionListener="#{kundeController.doDeleteMitarbeiter(mitarbeiter)}" />
				</p:column>
				<p:column style="width:15">

					<p:commandButton icon="ui-icon-pencil"
						action="#{kundeController.doEditMitarbeiter(mitarbeiter)}" id="cmdEdit" />
				<p:tooltip for="cmdEdit" >Mitarbeiter bearbeiten</p:tooltip>
				</p:column>
		
				<p:column style="width:15">

					<p:commandButton icon="ui-icon-mail-closed" id="cmdMail"
						action="#{kundeController.doMitarbeiterMail(mitarbeiter)}" />
						<p:tooltip for="cmdMail">E-Mail an Mitarbeiter senden</p:tooltip>
				</p:column>
				<p:column headerText="Zuname" sortBy="zuname"
					filterBy="#{mitarbeiter.zuname}" filterMatchMode="contains">
	    	           #{mitarbeiter.zuname}
    	    	</p:column>
				<p:column headerText="Vorname" sortBy="vorname"
					filterBy="#{mitarbeiter.vorname}" filterMatchMode="contains">
               #{mitarbeiter.vorname}
        	</p:column>
				<p:column headerText="Telefon" sortBy="telefon">
	    	           #{mitarbeiter.telefon}
    	    	</p:column>
				<p:column headerText="Mobil" sortBy="mobil">
	    	           #{mitarbeiter.mobil}
    	    	</p:column>
				<p:column headerText="E-Mail">
					<h:outputText value="#{mitarbeiter.email}" />
				</p:column>
				<p:column headerText="Telefax" sortBy="telefax">
	    	           #{mitarbeiter.telefax}
    	    	</p:column>

			</p:dataTable>
		</h:form>
	</ui:define>
</ui:composition>
</html>

src/main/webapp/Kunden.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


<ui:composition template="WEB-INF/templates/template.xhtml">

	<ui:define name="content">
		<h:form>
	
	<p:commandButton value="Neuer Kunde" icon="ui-icon-plus"
				action="#{kundeUebersichtController.doAddKunde()}" ajax="false" />
	<hr/>
		<p:dataTable var="kunde" value="#{kundeUebersichtController.kunden}" filteredValue="#{kundeUebersichtController.filteredKunden}"
			paginator="true" rows="5"
			>
			<f:facet name="header">
               Kunden
        </f:facet>
		<p:column style="width:15">
					<p:commandButton icon="ui-icon-trash" onclick="confirmation.show()"
						actionListener="#{kundeUebersichtController.doDeleteKunde(kunde)}" />
				</p:column>
			<p:column style="width:15">
					<p:commandButton  icon="ui-icon-pencil"
						action="#{kundeUebersichtController.doEditKunde(kunde)}" />
				</p:column>
			<p:column headerText="Kunde" sortBy="kdName"
			filterBy="#{kunde.kdName}" filterMatchMode="contains"
			>
              <h:commandLink action = "#{kundeUebersichtController.doShowKunde(kunde)}"> #{kunde.kdName}</h:commandLink>
        	</p:column>
			<p:column headerText="Anschrift">
               #{kunde.anschrift}
        	</p:column>
			<p:column headerText="Ort" sortBy="#{kunde.ort}"
				filterBy="#{kunde.ort}" filterMatchMode="contains">
				<h:outputText value="#{kunde.ort}" />
			</p:column>
			<p:column headerText="Telefon">
               #{kunde.telefon}
	        </p:column>
			<p:column headerText="Mail">
        	       #{kunde.email}
        	</p:column>
        	
		</p:dataTable>
		</h:form>
	</ui:define>
</ui:composition>
</html>

src/main/webapp/Mitarbeiter.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


<ui:composition template="WEB-INF/templates/template.xhtml">
	<ui:define name="content">

		<h:head>
		<title>Mitarbeiter bearbeiten - supportTX</title>
		</h:head>	
		<h:form>
			<p:commandButton value="Speichern" icon="ui-icon-disk"
				action="#{mitarbeiterController.doSave()}" ajax="false" />
			<p:commandButton value="Abbrechen" icon="ui-icon-close"
				action="#{mitarbeiterController.doCancel()}" ajax="false" />
			<hr/>
				<h3 style="padding-left:20">  Mitarbeiter bearbeiten</h3>
			<p:panelGrid columns="2">
				<p:outputLabel id="lblVorname">Vorname:</p:outputLabel>
				<p:inputText value="#{mitarbeiterController.mitarbeiter.vorname}"
					label="lblVorname" size="40" placeholder="Vorname" />
				<p:outputLabel id="lblZuname">Zuname:</p:outputLabel>
				<p:inputText value="#{mitarbeiterController.mitarbeiter.zuname}"
					label="lblZuname" placeholder="Zuname" size="40" />
				<p:outputLabel id="lblMobil">Mobil:</p:outputLabel>
				<p:inputText value="#{mitarbeiterController.mitarbeiter.mobil}"
					label="lblMobil" placeholder="Mobil-Rufnummer" size="40" />

				<p:outputLabel id="lblTelefon">Telefon:</p:outputLabel>
				<p:inputText value="#{mitarbeiterController.mitarbeiter.telefon}"
					label="lblTelefon" placeholder="Telefon" size="40" />

				<p:outputLabel id="lblemail">E-Mail:</p:outputLabel>
				<p:inputText value="#{mitarbeiterController.mitarbeiter.email}"
					label="lblemail" placeholder="E-Mail" size="40" />
				<p:outputLabel id="lblTelefax">Telefax:</p:outputLabel>
				<p:inputText value="#{mitarbeiterController.mitarbeiter.telefax}"
					label="lbltelefax" placeholder="Telefax" size="40" />


			</p:panelGrid>
		</h:form>


	</ui:define>
</ui:composition>
</html>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


<ui:composition template="WEB-INF/templates/template.xhtml">

	<ui:define name="content">
		<h:form>
			<h1>supportTX</h1>
		</h:form>

	</ui:define>
</ui:composition>
</html>